### ISSUE TITLE
torch.hub has no attribute 'get_dir'

### ISSUE THREAD

**Issue by Wangman1** [fudan-zvg/SETR#12]
torch.hub has no attribute 'get_dir'

**Comment by VictorLlu** [comment]
Could you give us more detailed error information because we think this error results from a low version of Pytorch. 

You can try from `torch.hub import get_dir` directly in a Python console. If you succeed please inform us again. You can also refer to the official Pytorch document https://pytorch.org/docs/stable/hub.html#torch.hub.get_dir for help. Thank you for your support!
