### ISSUE TITLE
Auxiliary loss

### ISSUE THREAD

**Issue by yangshushuaige** [fudan-zvg/SETR#20]
Thank you for your great work. Auxiliary segmentation loss helps the model training and may lead to significant performance improvement. Can you provide some related results w/o auxiliary loss?

**Comment by yangshushuaige** [comment]
For SETR-Naive and SETR-PUP only using the final output of transformer, do you also use the Auxiliary segmentation loss to supervise intermediate layers of transformer?

**Comment by lzrobots** [comment]
`Thank you for your great work. Auxiliary segmentation loss helps the model training and may lead to significant performance improvement. Can you provide some related results w/o auxiliary loss?`

Thank you. We didn't report the results w/o auxiliary loss due to the space issue and you can have a try without the auxiliary loss.

`For SETR-Naive and SETR-PUP only using the final output of transformer, do you also use the Auxiliary segmentation loss to supervise intermediate layers of transformer?`

Yes. Please take a look of the config file 

`https://github.com/fudan-zvg/SETR/blob/main/configs/SETR/SETR_PUP_768x768_80k_cityscapes_bs_8.py#L11-L71` and
`https://github.com/fudan-zvg/SETR/blob/main/configs/SETR/SETR_Naive_768x768_40k_cityscapes_bs_8.py#L10-L55`
